# Generated by Django 4.2 on 2025-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_classroom_guardian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='students',
            new_name='student',
        ),
    ]
